import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StoreProvider from "@/redux/storeProvider";
import QueryProvider from "@/providers/QueryProvider";

const monteSerrat = Montserrat({ 
  variable: "--font-monteserrat",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={`${monteSerrat.variable}`}
      >
        <main>
          <QueryProvider>
            <StoreProvider>
              <Navbar />
              {children}
            </StoreProvider>
          </QueryProvider>
        </main>
      </body>
    </html>
  );
}
